version: 0.0
os: linux
files:
  - source: /
    destination: /home/ec2-user/app
hooks:
  AfterInstall:
    - runas: ec2-user
      timeout: 300
      script: |
        #!/bin/bash
        set -e

        IMAGE_TAG="#{BuildVariables.IMAGE_TAG}"
        APP_NAME="$APP_NAME"
        IMAGE_URI="$AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/$APP_NAME:$IMAGE_TAG"

        echo "Logging in to ECR..."
        aws ecr get-login-password --region $AWS_REGION | docker login --username AWS --password-stdin $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com

        echo "Pulling latest image..."
        docker pull $IMAGE_URI

        echo "Stopping old container..."
        docker stop $APP_NAME || true
        docker rm $APP_NAME || true

        echo "Running new container..."
        docker run -d --name $APP_NAME -p 80:80 $IMAGE_URI
