apiVersion: v1
kind: Service
metadata:
  name: todo-frontend-svc
  namespace: fargate-profile
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-scheme: internet-facing
spec:
  selector:
    app: todo-frontend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: LoadBalancer
