apiVersion: apps/v1
kind: Deployment
metadata:
  name: todo-frontend
  namespace: fargate-profile
spec:
  replicas: 1
  selector:
    matchLabels:
      app: todo-frontend
  template:
    metadata:
      labels:
        app: todo-frontend
    spec:
      containers:
        - name: todo-frontend
          image: 706712229921.dkr.ecr.us-east-1.amazonaws.com/todoapp/frontend:20
          ports:
            - containerPort: 80
